export const APP_CONFIG = {
  NOTE_TTL_HOURS: 24,
  VISIBILITY_RADIUS_METERS: 100,
  PRESENCE_RADIUS_METERS: 100,
  PRESENCE_ACTIVE_WINDOW_MINUTES: 5,
  MAX_NOTE_LENGTH: 120,
  LOCATION_DECIMAL_PRECISION: 4,
  REPORT_AUTO_HIDE_THRESHOLD: 3,
  MAX_NOTES_PER_USER_PER_HOUR: 5,
  MAX_REPORTS_PER_USER_PER_HOUR: 20,
  MAX_PUSH_NOTIFICATIONS_PER_USER_PER_HOUR: 5
} as const;

